<a href="https://colab.research.google.com/github/carsonasmith17/DS-2002-Labs-HW/blob/main/DS2002Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import pandas as pd
import numpy as np

df = pd.read_csv('anxiety_and_depression.csv')
df.head(20)

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,Low CI,High CI,Confidence Interval,Quartile Range
0,Symptoms of Depressive Disorder,National Estimate,United States,United States,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,23.5,22.7,24.3,22.7 - 24.3,NaN
1,Symptoms of Depressive Disorder,By Age,United States,18 - 29 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,32.7,30.2,35.2,30.2 - 35.2,NaN
2,Symptoms of Depressive Disorder,By Age,United States,30 - 39 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,25.7,24.1,27.3,24.1 - 27.3,NaN
3,Symptoms of Depressive Disorder,By Age,United States,40 - 49 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,24.8,23.3,26.2,23.3 - 26.2,NaN
4,Symptoms of Depressive Disorder,By Age,United States,50 - 59 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,23.2,21.5,25.0,21.5 - 25.0,NaN
5,Symptoms of Depressive Disorder,By Age,United States,60 - 69 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,18.4,17.0,19.7,17.0 - 19.7,NaN
6,Symptoms of Depressive Disorder,By Age,United States,70 - 79 years,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,13.6,11.8,15.5,11.8 - 15.5,NaN
7,Symptoms of Depressive Disorder,By Age,United States,80 years and above,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,14.4,9.0,21.4,9.0 - 21.4,NaN
8,Symptoms of Depressive Disorder,By Sex,United States,Male,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,20.8,19.6,22.0,19.6 - 22.0,NaN
9,Symptoms of Depressive Disorder,By Sex,United States,Female,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,26.1,25.2,27.1,25.2 - 27.1,NaN
10,Symptoms of Depressive Disorder,By Race/Hispanic ethnicity,United States,Hispanic or Latino,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,29.4,26.8,32.1,26.8 - 32.1,NaN
11,Symptoms of Depressive Disorder,By Race/Hispanic ethnicity,United States,"Non-Hispanic White, single race",1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,21.4,20.6,22.1,20.6 - 22.1,NaN
12,Symptoms of Depressive Disorder,By Race/Hispanic ethnicity,United States,"Non-Hispanic Black, single race",1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,25.6,23.7,27.5,23.7 - 27.5,NaN
13,Symptoms of Depressive Disorder,By Race/Hispanic ethnicity,United States,"Non-Hispanic Asian, single race",1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,23.6,20.3,27.1,20.3 - 27.1,NaN
14,Symptoms of Depressive Disorder,By Race/Hispanic ethnicity,United States,"Non-Hispanic, other races and multiple races",1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,28.3,24.8,32.0,24.8 - 32.0,NaN
15,Symptoms of Depressive Disorder,By Education,United States,Less than a high school diploma,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,32.7,27.8,38.0,27.8 - 38.0,NaN
16,Symptoms of Depressive Disorder,By Education,United States,High school diploma or GED,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,25.4,23.9,26.9,23.9 - 26.9,NaN
17,Symptoms of Depressive Disorder,By Education,United States,Some college/Associate's degree,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,25.6,24.4,26.9,24.4 - 26.9,NaN
18,Symptoms of Depressive Disorder,By Education,United States,Bachelor's degree or higher,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,17.6,16.8,18.4,16.8 - 18.4,NaN
19,Symptoms of Depressive Disorder,By State,Alabama,Alabama,1,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,18.6,14.6,23.1,14.6 - 23.1,16.5 - 20.7

In [30]:
df.shape

(16794, 14)

In [58]:
len(df)

16794

In [55]:
len(df.columns)

13

In [61]:
def csv_to_json(csv_file, json_file):

    df = pd.read_csv('anxiety_and_depression.csv')

    df.to_json(json_file, orient='records', lines=True)

csv_file = 'anxiety_and_depression.csv'
json_file = 'json_anxiety_and_depression.json'
csv_to_json(csv_file, json_file)

In [19]:
unique_states = df['State'].unique()
print(unique_states)

['United States' 'Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California'
 'Colorado' 'Connecticut' 'Delaware' 'District of Columbia' 'Florida'
 'Georgia' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island'
 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont'
 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']

52 total values for 'State' - - includes all states + District of Columbia & 'United States'

In [13]:
unique_indicators = df['Indicator'].unique()
print(unique_indicators)

['Symptoms of Depressive Disorder' 'Symptoms of Anxiety Disorder'
 'Symptoms of Anxiety Disorder or Depressive Disorder']

In [14]:
unique_groups = df['Group'].unique()
print(unique_groups)

['National Estimate' 'By Age' 'By Sex' 'By Race/Hispanic ethnicity'
 'By Education' 'By State' 'By Disability status' 'By Gender identity'
 'By Sexual orientation']

In [15]:
unique_subgroups = df['Subgroup'].unique()
print(unique_subgroups)

['United States' '18 - 29 years' '30 - 39 years' '40 - 49 years'
 '50 - 59 years' '60 - 69 years' '70 - 79 years' '80 years and above'
 'Male' 'Female' 'Hispanic or Latino' 'Non-Hispanic White, single race'
 'Non-Hispanic Black, single race' 'Non-Hispanic Asian, single race'
 'Non-Hispanic, other races and multiple races'
 'Less than a high school diploma' 'High school diploma or GED'
 "Some college/Associate's degree" "Bachelor's degree or higher" 'Alabama'
 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado' 'Connecticut'
 'Delaware' 'District of Columbia' 'Florida' 'Georgia' 'Hawaii' 'Idaho'
 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine'
 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi'
 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey'
 'New Mexico' 'New York' 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma'
 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina' 'South Dakota'
 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia' 'Washington'
 'West Virginia' 'Wisconsin' 'Wyoming' 'With disability'
 'Without disability' 'Cis-gender male' 'Cis-gender female' 'Transgender'
 'Gay or lesbian' 'Straight' 'Bisexual']

In [16]:
unique_phases = df['Phase'].unique()
print(unique_phases)

['1' '-1' '2' '3.0 (Oct 28 - Dec 21)' '3.0 (Jan 6 - Mar 29)' '3.1' '3.2'
 '3.3' '3.4' '3.5' '3.6' '3.7' '3.8' '3.9' '4' '4.1' '4.2']

In [17]:
unique_tp = df['Time Period'].unique()
print(unique_tp)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72]

*****delete time period label column all together******

renamed "state" to "location", seeing as some of the unique values in "state" included "United states" and "district of columbia"

In [48]:
df.head()

,Indicator,Group,State,Subgroup,Phase,Time Period Label,Time Period Start Date,Time Period End Date,Value,Low CI,High CI,Confidence Interval,Quartile Range
0,Symptoms of Depressive Disorder,National Estimate,United States,United States,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,23.5,22.7,24.3,22.7 - 24.3,NaN
1,Symptoms of Depressive Disorder,By Age,United States,18 - 29 years,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,32.7,30.2,35.2,30.2 - 35.2,NaN
2,Symptoms of Depressive Disorder,By Age,United States,30 - 39 years,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,25.7,24.1,27.3,24.1 - 27.3,NaN
3,Symptoms of Depressive Disorder,By Age,United States,40 - 49 years,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,24.8,23.3,26.2,23.3 - 26.2,NaN
4,Symptoms of Depressive Disorder,By Age,United States,50 - 59 years,1,"Apr 23 - May 5, 2020",04/23/2020,05/05/2020,23.2,21.5,25.0,21.5 - 25.0,NaN

In [51]:
new_dataframe = df.drop('Time Period Label', axis=1)
new_dataframe.rename(columns={'State': 'Location'}, inplace=True)
print(new_dataframe.head().to_string())

                         Indicator              Group       Location       Subgroup Phase Time Period Start Date Time Period End Date  Value  Low CI  High CI Confidence Interval Quartile Range
0  Symptoms of Depressive Disorder  National Estimate  United States  United States     1             04/23/2020           05/05/2020   23.5    22.7     24.3         22.7 - 24.3            NaN
1  Symptoms of Depressive Disorder             By Age  United States  18 - 29 years     1             04/23/2020           05/05/2020   32.7    30.2     35.2         30.2 - 35.2            NaN
2  Symptoms of Depressive Disorder             By Age  United States  30 - 39 years     1             04/23/2020           05/05/2020   25.7    24.1     27.3         24.1 - 27.3            NaN
3  Symptoms of Depressive Disorder             By Age  United States  40 - 49 years     1             04/23/2020           05/05/2020   24.8    23.3     26.2         23.3 - 26.2            NaN
4  Symptoms of Depressive Disorder             By Age  United States  50 - 59 years     1             04/23/2020           05/05/2020   23.2    21.5     25.0         21.5 - 25.0            NaN

In [63]:

new_column_order = ['Location','Indicator', 'Group', 'Subgroup', 'Phase', 'Time Period Start Date','Time Period End Date', 'Value', 'Low CI', 'High CI', 'Confidence Interval', 'Quartile Range']

reordered_df = new_dataframe[new_column_order]

print(reordered_df.head().to_string())

        Location                        Indicator              Group       Subgroup Phase Time Period Start Date Time Period End Date  Value  Low CI  High CI Confidence Interval Quartile Range
0  United States  Symptoms of Depressive Disorder  National Estimate  United States     1             04/23/2020           05/05/2020   23.5    22.7     24.3         22.7 - 24.3            NaN
1  United States  Symptoms of Depressive Disorder             By Age  18 - 29 years     1             04/23/2020           05/05/2020   32.7    30.2     35.2         30.2 - 35.2            NaN
2  United States  Symptoms of Depressive Disorder             By Age  30 - 39 years     1             04/23/2020           05/05/2020   25.7    24.1     27.3         24.1 - 27.3            NaN
3  United States  Symptoms of Depressive Disorder             By Age  40 - 49 years     1             04/23/2020           05/05/2020   24.8    23.3     26.2         23.3 - 26.2            NaN
4  United States  Symptoms of Depressive Disorder             By Age  50 - 59 years     1             04/23/2020           05/05/2020   23.2    21.5     25.0         21.5 - 25.0            NaN

In [56]:
len(reordered_df.columns)

12

In [59]:
len(reordered_df)

16794

In [171]:
reordered_df.to_csv('reordered_anxiety_depression.csv', index=False)

put group and subgroup next to each other becuse they made more sense together, started with location first becasue it seemed loosely related to the other data in the dataframe; was most logical order (in my opinion)

In [117]:
def csv_to_json(csv_file, json_file):

    df2 = pd.read_csv('Youth_Tobacco_Survey.csv')

    df2.to_json(json_file, orient='records', lines=True)

csv_file = 'Youth_Tobacco_Survey.csv'
json_file = 'YTS.json'
csv_to_json(csv_file, json_file)

In [173]:
import json

def load_json(YTS_json):
    data = []
    with open('YTS.json', 'r') as f:

        for line in f:

            data.append(json.loads(line))
    return data

dataset = load_json('YTS.json')

df2 = pd.DataFrame(dataset)
display(df2)

,YEAR,LocationAbbr,LocationDesc,TopicType,TopicDesc,MeasureDesc,DataSource,Response,Data_Value_Unit,Data_Value_Type,...,GeoLocation,TopicTypeId,TopicId,MeasureId,StratificationID1,StratificationID2,StratificationID3,StratificationID4,SubMeasureID,DisplayOrder
0,2004,OH,Ohio,Tobacco Use – Survey Data,Cigarette Use (Youth),Smoking Status,YTS,Ever,%,Percentage,...,"(40.060210141, -82.404260056)",BEH,106BEH,166SSA,1GEN,8AGE,6RAC,1EDU,YTS08,8
1,2008,AL,Alabama,Tobacco Use – Survey Data,Cigarette Use (Youth),Smoking Status,YTS,Ever,%,Percentage,...,"(32.840571122, -86.631860762)",BEH,106BEH,166SSA,3GEN,8AGE,6RAC,2EDU,YTS08,8
2,2015,WV,West Virginia,Tobacco Use – Survey Data,Smokeless Tobacco Use (Youth),User Status,YTS,Frequent,%,Percentage,...,"(38.665510202, -80.712640135)",BEH,151BEH,169USS,2GEN,8AGE,6RAC,2EDU,YTS12,12
3,2005,IL,Illinois,Tobacco Use – Survey Data,Cigarette Use (Youth),Smoking Status,YTS,Ever,%,Percentage,...,"(40.485010283, -88.997710178)",BEH,106BEH,166SSA,1GEN,8AGE,6RAC,1EDU,YTS08,8
4,2005,CT,Connecticut,Tobacco Use – Survey Data,Smokeless Tobacco Use (Youth),User Status,YTS,Ever,%,Percentage,...,"(41.56266102, -72.649840952)",BEH,151BEH,169USS,2GEN,8AGE,6RAC,2EDU,YTS11,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10595,2002,KS,Kansas,Tobacco Use – Survey Data,Smokeless Tobacco Use (Youth),User Status,YTS,Frequent,%,Percentage,...,"(38.3477403, -98.200781227)",BEH,151BEH,169USS,1GEN,8AGE,6RAC,1EDU,YTS12,12
10596,2015,IL,Illinois,Tobacco Use – Survey Data,Cigarette Use (Youth),Smoking Status,YTS,Frequent,%,Percentage,...,"(40.485010283, -88.997710178)",BEH,106BEH,166SSA,2GEN,8AGE,6RAC,2EDU,YTS09,9
10597,2010,WI,Wisconsin,Tobacco Use – Survey Data,Cessation (Youth),Quit Attempt in Past Year Among Current Cigare...,YTS,None,%,Percentage,...,"(44.393191174, -89.816370742)",BEH,105BEH,169QUA,3GEN,8AGE,6RAC,1EDU,YTS06,6
10598,2009,LA,Louisiana,Tobacco Use – Survey Data,Cigarette Use (Youth),Smoking Status,YTS,Current,%,Percentage,...,"(31.312660644, -92.445680071)",BEH,106BEH,166SSA,3GEN,8AGE,6RAC,1EDU,YTS07,7
10599,2010,DE,Delaware,Tobacco Use – Survey Data,Cigarette Use (Youth),Smoking Status,YTS,Ever,%,Percentage,...,"(39.008830667, -75.577741168)",BEH,106BEH,166SSA,3GEN,8AGE,6RAC,2EDU,YTS08,8

In [163]:
df2.columns

Index(['YEAR', 'LocationAbbr', 'LocationDesc', 'TopicType', 'TopicDesc',
       'MeasureDesc', 'DataSource', 'Response', 'Data_Value_Unit',
       'Data_Value_Type', 'Data_Value', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Data_Value_Std_Err', 'Low_Confidence_Limit',
       'High_Confidence_Limit', 'Sample_Size', 'Gender', 'Race', 'Age',
       'Education', 'GeoLocation', 'TopicTypeId', 'TopicId', 'MeasureId',
       'StratificationID1', 'StratificationID2', 'StratificationID3',
       'StratificationID4', 'SubMeasureID', 'DisplayOrder'],
      dtype='object')

In [119]:
df2.shape

(10600, 31)

In [120]:
len(df2)

10600

In [121]:
len(df2.columns)

31

In [133]:
new_dataset = df2.drop('LocationAbbr', axis=1)

In [137]:
new_dataset2 = new_dataset.drop('DataSource', axis=1)

In [138]:
new_dataset3 = new_dataset2.drop('Data_Value_Type', axis=1)

In [141]:
new_dataset4 = new_dataset3.drop('TopicType', axis=1)

intuitive -- impliled buy the percentage symbol

In [142]:
print(new_dataset4.head().to_string())

   YEAR   LocationDesc                      TopicDesc     MeasureDesc  Response Data_Value_Unit  Data_Value Data_Value_Footnote_Symbol Data_Value_Footnote  Data_Value_Std_Err  Low_Confidence_Limit  High_Confidence_Limit  Sample_Size   Gender       Race       Age      Education                    GeoLocation TopicTypeId TopicId MeasureId StratificationID1 StratificationID2 StratificationID3 StratificationID4 SubMeasureID  DisplayOrder
0  2004           Ohio          Cigarette Use (Youth)  Smoking Status      Ever               %        32.2                       None                None                 3.2                  25.8                   38.5       1377.0  Overall  All Races  All Ages  Middle School  (40.060210141, -82.404260056)         BEH  106BEH    166SSA              1GEN              8AGE              6RAC              1EDU        YTS08             8
1  2008        Alabama          Cigarette Use (Youth)  Smoking Status      Ever               %        47.8                       None                None                 2.9                  42.1                   53.5        654.0   Female  All Races  All Ages    High School  (32.840571122, -86.631860762)         BEH  106BEH    166SSA              3GEN              8AGE              6RAC              2EDU        YTS08             8
2  2015  West Virginia  Smokeless Tobacco Use (Youth)     User Status  Frequent               %        12.7                       None                None                 1.9                   9.0                   16.4        781.0     Male  All Races  All Ages    High School  (38.665510202, -80.712640135)         BEH  151BEH    169USS              2GEN              8AGE              6RAC              2EDU        YTS12            12
3  2005       Illinois          Cigarette Use (Youth)  Smoking Status      Ever               %        28.5                       None                None                 2.2                  24.2                   32.8       1323.0  Overall  All Races  All Ages  Middle School  (40.485010283, -88.997710178)         BEH  106BEH    166SSA              1GEN              8AGE              6RAC              1EDU        YTS08             8
4  2005    Connecticut  Smokeless Tobacco Use (Youth)     User Status      Ever               %        20.5                       None                None                 2.3                  16.0                   25.1        973.0     Male  All Races  All Ages    High School   (41.56266102, -72.649840952)         BEH  151BEH    169USS              2GEN              8AGE              6RAC              2EDU        YTS11            11

In [145]:
column_names2 = new_dataset4.columns.tolist()
print(column_names2)

['YEAR', 'LocationDesc', 'TopicDesc', 'MeasureDesc', 'Response', 'Data_Value_Unit', 'Data_Value', 'Data_Value_Footnote_Symbol', 'Data_Value_Footnote', 'Data_Value_Std_Err', 'Low_Confidence_Limit', 'High_Confidence_Limit', 'Sample_Size', 'Gender', 'Race', 'Age', 'Education', 'GeoLocation', 'TopicTypeId', 'TopicId', 'MeasureId', 'StratificationID1', 'StratificationID2', 'StratificationID3', 'StratificationID4', 'SubMeasureID', 'DisplayOrder']

In [148]:
new_column_order2 = ['YEAR', 'LocationDesc', 'TopicDesc', 'MeasureDesc', 'Response', 'Data_Value', 'Data_Value_Unit', 'Data_Value_Footnote_Symbol', 'Data_Value_Footnote', 'Data_Value_Std_Err', 'Low_Confidence_Limit', 'High_Confidence_Limit', 'Sample_Size', 'Gender', 'Race', 'Age', 'Education', 'GeoLocation', 'TopicTypeId', 'TopicId', 'MeasureId', 'StratificationID1', 'StratificationID2', 'StratificationID3', 'StratificationID4', 'SubMeasureID', 'DisplayOrder']

YTSreordered_df = new_dataset4[new_column_order2]

print(YTSreordered_df.head().to_string())

   YEAR   LocationDesc                      TopicDesc     MeasureDesc  Response  Data_Value Data_Value_Unit Data_Value_Footnote_Symbol Data_Value_Footnote  Data_Value_Std_Err  Low_Confidence_Limit  High_Confidence_Limit  Sample_Size   Gender       Race       Age      Education                    GeoLocation TopicTypeId TopicId MeasureId StratificationID1 StratificationID2 StratificationID3 StratificationID4 SubMeasureID  DisplayOrder
0  2004           Ohio          Cigarette Use (Youth)  Smoking Status      Ever        32.2               %                       None                None                 3.2                  25.8                   38.5       1377.0  Overall  All Races  All Ages  Middle School  (40.060210141, -82.404260056)         BEH  106BEH    166SSA              1GEN              8AGE              6RAC              1EDU        YTS08             8
1  2008        Alabama          Cigarette Use (Youth)  Smoking Status      Ever        47.8               %                       None                None                 2.9                  42.1                   53.5        654.0   Female  All Races  All Ages    High School  (32.840571122, -86.631860762)         BEH  106BEH    166SSA              3GEN              8AGE              6RAC              2EDU        YTS08             8
2  2015  West Virginia  Smokeless Tobacco Use (Youth)     User Status  Frequent        12.7               %                       None                None                 1.9                   9.0                   16.4        781.0     Male  All Races  All Ages    High School  (38.665510202, -80.712640135)         BEH  151BEH    169USS              2GEN              8AGE              6RAC              2EDU        YTS12            12
3  2005       Illinois          Cigarette Use (Youth)  Smoking Status      Ever        28.5               %                       None                None                 2.2                  24.2                   32.8       1323.0  Overall  All Races  All Ages  Middle School  (40.485010283, -88.997710178)         BEH  106BEH    166SSA              1GEN              8AGE              6RAC              1EDU        YTS08             8
4  2005    Connecticut  Smokeless Tobacco Use (Youth)     User Status      Ever        20.5               %                       None                None                 2.3                  16.0                   25.1        973.0     Male  All Races  All Ages    High School   (41.56266102, -72.649840952)         BEH  151BEH    169USS              2GEN              8AGE              6RAC              2EDU        YTS11            11

In [153]:
YTS_reordered = YTSreordered_df.drop('Data_Value_Footnote_Symbol', axis=1)

In [157]:
display(YTS_reordered)

,YEAR,LocationDesc,TopicDesc,MeasureDesc,Response,Data_Value,Data_Value_Unit,Data_Value_Footnote,Data_Value_Std_Err,Low_Confidence_Limit,...,GeoLocation,TopicTypeId,TopicId,MeasureId,StratificationID1,StratificationID2,StratificationID3,StratificationID4,SubMeasureID,DisplayOrder
0,2004,Ohio,Cigarette Use (Youth),Smoking Status,Ever,32.2,%,None,3.2,25.8,...,"(40.060210141, -82.404260056)",BEH,106BEH,166SSA,1GEN,8AGE,6RAC,1EDU,YTS08,8
1,2008,Alabama,Cigarette Use (Youth),Smoking Status,Ever,47.8,%,None,2.9,42.1,...,"(32.840571122, -86.631860762)",BEH,106BEH,166SSA,3GEN,8AGE,6RAC,2EDU,YTS08,8
2,2015,West Virginia,Smokeless Tobacco Use (Youth),User Status,Frequent,12.7,%,None,1.9,9.0,...,"(38.665510202, -80.712640135)",BEH,151BEH,169USS,2GEN,8AGE,6RAC,2EDU,YTS12,12
3,2005,Illinois,Cigarette Use (Youth),Smoking Status,Ever,28.5,%,None,2.2,24.2,...,"(40.485010283, -88.997710178)",BEH,106BEH,166SSA,1GEN,8AGE,6RAC,1EDU,YTS08,8
4,2005,Connecticut,Smokeless Tobacco Use (Youth),User Status,Ever,20.5,%,None,2.3,16.0,...,"(41.56266102, -72.649840952)",BEH,151BEH,169USS,2GEN,8AGE,6RAC,2EDU,YTS11,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10595,2002,Kansas,Smokeless Tobacco Use (Youth),User Status,Frequent,0.3,%,None,0.2,0.0,...,"(38.3477403, -98.200781227)",BEH,151BEH,169USS,1GEN,8AGE,6RAC,1EDU,YTS12,12
10596,2015,Illinois,Cigarette Use (Youth),Smoking Status,Frequent,2.7,%,None,0.7,1.3,...,"(40.485010283, -88.997710178)",BEH,106BEH,166SSA,2GEN,8AGE,6RAC,2EDU,YTS09,9
10597,2010,Wisconsin,Cessation (Youth),Quit Attempt in Past Year Among Current Cigare...,None,NaN,%,Data in these cells have been suppressed becau...,NaN,NaN,...,"(44.393191174, -89.816370742)",BEH,105BEH,169QUA,3GEN,8AGE,6RAC,1EDU,YTS06,6
10598,2009,Louisiana,Cigarette Use (Youth),Smoking Status,Current,10.1,%,None,1.4,7.4,...,"(31.312660644, -92.445680071)",BEH,106BEH,166SSA,3GEN,8AGE,6RAC,1EDU,YTS07,7
10599,2010,Delaware,Cigarette Use (Youth),Smoking Status,Ever,45.8,%,None,2.2,41.4,...,"(39.008830667, -75.577741168)",BEH,106BEH,166SSA,3GEN,8AGE,6RAC,2EDU,YTS08,8

In [159]:
YTS_reordered2 = YTS_reordered.drop('Data_Value_Footnote', axis=1)

In [160]:
print(YTS_reordered2.head().to_string())

   YEAR   LocationDesc                      TopicDesc     MeasureDesc  Response  Data_Value Data_Value_Unit  Data_Value_Std_Err  Low_Confidence_Limit  High_Confidence_Limit  Sample_Size   Gender       Race       Age      Education                    GeoLocation TopicTypeId TopicId MeasureId StratificationID1 StratificationID2 StratificationID3 StratificationID4 SubMeasureID  DisplayOrder
0  2004           Ohio          Cigarette Use (Youth)  Smoking Status      Ever        32.2               %                 3.2                  25.8                   38.5       1377.0  Overall  All Races  All Ages  Middle School  (40.060210141, -82.404260056)         BEH  106BEH    166SSA              1GEN              8AGE              6RAC              1EDU        YTS08             8
1  2008        Alabama          Cigarette Use (Youth)  Smoking Status      Ever        47.8               %                 2.9                  42.1                   53.5        654.0   Female  All Races  All Ages    High School  (32.840571122, -86.631860762)         BEH  106BEH    166SSA              3GEN              8AGE              6RAC              2EDU        YTS08             8
2  2015  West Virginia  Smokeless Tobacco Use (Youth)     User Status  Frequent        12.7               %                 1.9                   9.0                   16.4        781.0     Male  All Races  All Ages    High School  (38.665510202, -80.712640135)         BEH  151BEH    169USS              2GEN              8AGE              6RAC              2EDU        YTS12            12
3  2005       Illinois          Cigarette Use (Youth)  Smoking Status      Ever        28.5               %                 2.2                  24.2                   32.8       1323.0  Overall  All Races  All Ages  Middle School  (40.485010283, -88.997710178)         BEH  106BEH    166SSA              1GEN              8AGE              6RAC              1EDU        YTS08             8
4  2005    Connecticut  Smokeless Tobacco Use (Youth)     User Status      Ever        20.5               %                 2.3                  16.0                   25.1        973.0     Male  All Races  All Ages    High School   (41.56266102, -72.649840952)         BEH  151BEH    169USS              2GEN              8AGE              6RAC              2EDU        YTS11            11

In [168]:
YTS_reordered2.shape

(10600, 25)

In [169]:
len(YTS_reordered2)

10600

In [170]:
len(YTS_reordered2.columns)

25

In [172]:
YTS_reordered2.to_csv('reordered_Youth_Tobacco_Survey.csv', index=False)